<?php
// payroll/lib/PayslipEmailer.php
//
// Emails the HTML payslip generated by PayslipGenerator.php to each employee
// in a pay run. Uses the first configured email_account for the company as
// the sending mailbox (decrypted via SecureVault). Per-employee delivery is
// recorded on pay_run_employees.payslip_emailed_at / payslip_email_error.

require_once __DIR__ . '/../../mail/lib/SecureVault.php';
require_once __DIR__ . '/../../mail/lib/SmtpSender.php';

/**
 * Email payslips for every employee in a run that has an email address and a
 * generated payslip on disk. Returns counts: ['sent' => n, 'skipped' => n, 'failed' => n].
 *
 * If $onlyMissing is true (default), employees who already have a successful
 * payslip_emailed_at are skipped — this lets the lock step retry without
 * re-spamming workers if the cron / button is hit twice.
 */
function emailPayslips(PDO $db, int $companyId, int $runId, bool $onlyMissing = true): array
{
    $result = ['sent' => 0, 'skipped' => 0, 'failed' => 0, 'errors' => []];

    $stmt = $db->prepare(
        "SELECT account_id, email_address, smtp_server, smtp_port, smtp_encryption,
                username, password_encrypted
         FROM email_accounts
         WHERE company_id = ? AND smtp_server IS NOT NULL AND smtp_server <> ''
         ORDER BY account_id ASC LIMIT 1"
    );
    $stmt->execute([$companyId]);
    $acc = $stmt->fetch(PDO::FETCH_ASSOC);
    if (!$acc) {
        throw new Exception('No SMTP-enabled email account configured for this company');
    }

    $stmtCo = $db->prepare("SELECT name FROM companies WHERE id = ?");
    $stmtCo->execute([$companyId]);
    $companyName = $stmtCo->fetchColumn() ?: 'Payroll';

    $stmt = $db->prepare(
        "SELECT pre.id, pre.employee_id, pre.payslip_path, pre.payslip_emailed_at,
                pre.net_cents, e.first_name, e.last_name, e.email,
                pr.name AS run_name, pr.period_start, pr.period_end, pr.pay_date
         FROM pay_run_employees pre
         JOIN employees e ON e.id = pre.employee_id
         JOIN pay_runs pr ON pr.id = pre.run_id
         WHERE pre.run_id = ? AND pre.company_id = ?"
    );
    $stmt->execute([$runId, $companyId]);
    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

    $pass = SecureVault::decrypt($acc['password_encrypted'] ?? '');

    $upd = $db->prepare(
        "UPDATE pay_run_employees
         SET payslip_emailed_at = ?, payslip_email_error = ?
         WHERE id = ?"
    );

    foreach ($rows as $row) {
        $empName = trim($row['first_name'] . ' ' . $row['last_name']);
        $to      = trim((string)$row['email']);

        if ($to === '' || empty($row['payslip_path'])) {
            $result['skipped']++;
            continue;
        }
        if ($onlyMissing && !empty($row['payslip_emailed_at'])) {
            $result['skipped']++;
            continue;
        }

        $absPath = realpath(__DIR__ . '/../..' . $row['payslip_path']);
        if (!$absPath || !is_file($absPath)) {
            $result['failed']++;
            $result['errors'][] = "$empName: payslip file not found";
            $upd->execute([null, 'payslip file not found', (int)$row['id']]);
            continue;
        }
        $body = file_get_contents($absPath);
        if ($body === false) {
            $result['failed']++;
            $result['errors'][] = "$empName: could not read payslip";
            $upd->execute([null, 'could not read payslip', (int)$row['id']]);
            continue;
        }

        $subject = 'Payslip: ' . $row['run_name']
                 . ' (' . date('d M Y', strtotime($row['period_start']))
                 . ' – ' . date('d M Y', strtotime($row['period_end'])) . ')';

        $send = SmtpSender::send([
            'host'       => $acc['smtp_server'],
            'port'       => (int)$acc['smtp_port'],
            'encryption' => $acc['smtp_encryption'],
            'username'   => $acc['username'],
            'password'   => $pass,
            'from'       => $acc['email_address'],
            'to'         => [$to],
            'subject'    => $subject,
            'html'       => $body,
        ]);

        if (!empty($send['ok'])) {
            $result['sent']++;
            $upd->execute([date('Y-m-d H:i:s'), null, (int)$row['id']]);
        } else {
            $result['failed']++;
            $err = $send['error'] ?? 'send failed';
            $result['errors'][] = "$empName: $err";
            $upd->execute([null, substr($err, 0, 255), (int)$row['id']]);
        }
    }

    return $result;
}
