<?php
// /qi/cron/generate_recurring.php
// Run daily: 0 2 * * * /usr/bin/php /path/to/qi/cron/generate_recurring.php

require_once __DIR__ . '/../../init.php';
require_once __DIR__ . '/../lib/SequenceAllocator.php';

try {
    // Find all active recurring invoices due today or earlier
    $stmt = $DB->prepare("
        SELECT * FROM recurring_invoices 
        WHERE active = 1 
        AND next_run_date <= CURDATE()
        AND (end_date IS NULL OR end_date >= CURDATE())
    ");
    $stmt->execute();
    $recurring = $stmt->fetchAll();

    foreach ($recurring as $rec) {
        try {
            $DB->beginTransaction();

            // Re-check the schedule UNDER LOCK: two overlapping cron runs (or
            // cron racing the manual "run now" endpoint) both read the same
            // due template above; without this the loser generated and POSTED
            // a duplicate invoice for the month.
            $stmt = $DB->prepare("SELECT next_run_date FROM recurring_invoices
                                   WHERE id = ? AND active = 1 FOR UPDATE");
            $stmt->execute([$rec['id']]);
            $currentNextRun = $stmt->fetchColumn();
            if ($currentNextRun === false || $currentNextRun > date('Y-m-d')) {
                $DB->rollBack();
                continue; // already generated by a concurrent run, or deactivated
            }
            $rec['next_run_date'] = $currentNextRun;

            // Fetch lines
            $stmt = $DB->prepare("SELECT * FROM recurring_invoice_lines WHERE recurring_invoice_id = ? ORDER BY sort_order");
            $stmt->execute([$rec['id']]);
            $lines = $stmt->fetchAll();

            // Generate invoice number using SequenceAllocator (race-safe)
            $alloc = new SequenceAllocator($DB);
            [$invoiceNumber, $seqNum] = $alloc->allocate((int)$rec['company_id'], 'invoice', null, true);

            // Calculate totals in INTEGER CENTS with the same per-line
            // rounding the posting engine uses — float totals here made the
            // header drift ±1c from the GL AR on rate/quantity fractions,
            // breaking the AR tie-out one cent per generated invoice.
            $subtotalC = 0;
            $discountC = 0;
            $taxC = 0;
            foreach ($lines as $line) {
                $qty = floatval($line['quantity']);
                $price = floatval($line['unit_price']);
                $disc = floatval($line['discount']);
                $taxRate = floatval($line['tax_rate']);
                $lineNetC = (int)round(($qty * $price - $disc) * 100);
                $lineVatC = (int)round($lineNetC * $taxRate / 100);
                $subtotalC += $lineNetC;
                $discountC += (int)round($disc * 100);
                $taxC += $lineVatC;
            }
            $subtotal = $subtotalC / 100;
            $discount = $discountC / 100;
            $tax = $taxC / 100;
            $total = ($subtotalC + $taxC) / 100;

            // Create invoice - use qi_settings for payment terms and default currency
            $issueDate = date('Y-m-d');
            $stmtTerms = $DB->prepare("SELECT default_payment_terms, default_currency FROM qi_settings WHERE company_id = ?");
            $stmtTerms->execute([$rec['company_id']]);
            $termsRow = $stmtTerms->fetch();
            $paymentDays = ($termsRow && $termsRow['default_payment_terms']) ? (int)$termsRow['default_payment_terms'] : 30;
            $dueDate = date('Y-m-d', strtotime("+{$paymentDays} days"));

            require_once __DIR__ . '/../lib/Currencies.php';
            $currency = Currencies::isValid($termsRow['default_currency'] ?? null) ? strtoupper($termsRow['default_currency']) : Currencies::BASE;
            $exchangeRate = 1.0;
            if ($currency !== Currencies::BASE) {
                require_once __DIR__ . '/../../finances/lib/CurrencyService.php';
                $svc = new CurrencyService($DB, (int)$rec['company_id']);
                $exchangeRate = (float)($svc->getRate($currency, $issueDate) ?? 0);
                if ($exchangeRate <= 0) {
                    error_log("Recurring cron: no {$currency} exchange rate for {$issueDate} (company {$rec['company_id']}); using 1.0");
                    $exchangeRate = 1.0;
                }
            }

            $stmt = $DB->prepare("
                INSERT INTO invoices (
                    company_id, invoice_number, customer_id,
                    issue_date, due_date, status,
                    subtotal, discount, tax, total, balance_due, currency, exchange_rate,
                    terms, notes, created_by
                ) VALUES (?, ?, ?, ?, ?, 'draft', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ");
            $stmt->execute([
                $rec['company_id'], $invoiceNumber, $rec['customer_id'],
                $issueDate, $dueDate,
                $subtotal, $discount, $tax, $total, $total, $currency, $exchangeRate,
                $rec['terms'] ?? '', 'Auto-generated from recurring: ' . ($rec['template_name'] ?? ('#' . $rec['id'])), $rec['created_by']
            ]);

            $invoiceId = $DB->lastInsertId();

            // Copy lines (line_total in the engine's integer-cents rounding)
            $sortOrder = 0;
            foreach ($lines as $line) {
                $qty = floatval($line['quantity']);
                $price = floatval($line['unit_price']);
                $disc = floatval($line['discount']);
                $taxRate = floatval($line['tax_rate']);

                $lineNetC = (int)round(($qty * $price - $disc) * 100);
                $lineVatC = (int)round($lineNetC * $taxRate / 100);
                $lineTotal = ($lineNetC + $lineVatC) / 100;

                $stmt = $DB->prepare("
                    INSERT INTO invoice_lines (
                        invoice_id, item_description, quantity, unit, unit_price, discount, tax_rate, tax_code_id, line_total, sort_order
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ");
                $stmt->execute([
                    $invoiceId, $line['item_description'], $qty, $line['unit'],
                    $price, $disc, $taxRate, $line['tax_code_id'] ?? null, $lineTotal, $sortOrder++
                ]);
            }

            // Calculate next run date
            $nextDate = date('Y-m-d', strtotime($rec['next_run_date']));
            
            switch ($rec['frequency']) {
                case 'weekly':
                    $nextDate = date('Y-m-d', strtotime($nextDate . ' +' . $rec['interval_count'] . ' weeks'));
                    break;
                case 'monthly':
                    $nextDate = date('Y-m-d', strtotime($nextDate . ' +' . $rec['interval_count'] . ' months'));
                    break;
                case 'quarterly':
                    $nextDate = date('Y-m-d', strtotime($nextDate . ' +' . ($rec['interval_count'] * 3) . ' months'));
                    break;
                case 'yearly':
                    $nextDate = date('Y-m-d', strtotime($nextDate . ' +' . $rec['interval_count'] . ' years'));
                    break;
            }

            $stmt = $DB->prepare("
                UPDATE recurring_invoices 
                SET next_run_date = ?, last_generated_date = NOW()
                WHERE id = ?
            ");
            $stmt->execute([$nextDate, $rec['id']]);

            // A generated recurring invoice is an intentional issuance:
            // transition it out of draft and post it to the GL inside this
            // transaction (rolls back the generation if posting fails).
            require_once __DIR__ . '/../lib/InvoiceLifecycle.php';
            $userId = $rec['created_by'] ?: 1;
            InvoiceLifecycle::issueInvoice($DB, (int)$rec['company_id'], (int)$userId, (int)$invoiceId);

            $DB->commit();

            echo "Generated invoice {$invoiceNumber} from recurring {$rec['id']}\n";

        } catch (Exception $e) {
            $DB->rollBack();
            error_log("Recurring generation failed for ID {$rec['id']}: " . $e->getMessage());
        }
    }

    echo "Cron completed. Processed " . count($recurring) . " recurring invoices.\n";

} catch (Exception $e) {
    error_log("Recurring cron error: " . $e->getMessage());
}